@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' LAYOUT_WITH_LEGEND()

title Учет сертификатов

System_Boundary(Магазин1, "1C:Учет сертификатов (Магазин 1)") {
  Container(Магазин1_Сертификат, "Подарочные сертификаты")
  Container(Магазин1_Реализация, "Реализация сертификатов")
  Container(Магазин1_Списание, "Списание сертификатов")
 }

System_Boundary(Магазин2, "1C:Учет сертификатов (Магазин 2)") {
  Container(Магазин2_Сертификат, "Подарочные сертификаты")
  Container(Магазин2_Реализация, "Реализация сертификатов")
  Container(Магазин2_Списание, "Списание сертификатов")
 }


System_Boundary(ГоловнаяБаза, "1C:Центральная база") {
  Container(ГоловнаяБаза_Сертификат, "Подарочные сертификаты")
  Container(ГоловнаяБаза_Реализация, "Реализация сертификатов")
  Container(ГоловнаяБаза_Списание, "Списание сертификатов")
 }

System_Ext(Раббит, "Rabbit MQ") {
  Container(Очередь, "Очередь", "Очередь сертификатов")

'Связи через kafka
Rel(Магазин1_Сертификат, Очередь, "", "Обмен сертификатами JSON")
Rel(Очередь, Магазин1_Сертификат, "", )
Rel(Магазин1_Реализация, Очередь, "", "Выгрузка реализаций сертификатов JSON")
Rel(Магазин1_Списание, Очередь, "", "Выгрузка списаний сертификатов JSON")


Rel(Магазин2_Сертификат, Очередь, "", "Обмен сертификатами JSON")
Rel(Очередь, Магазин2_Сертификат, "", )
Rel(Магазин2_Реализация, Очередь, "", "Выгрузка реализаций сертификатов JSON")
Rel(Магазин2_Списание, Очередь, "", "Выгрузка списаний сертификатов JSON")

Rel(Очередь, ГоловнаяБаза_Сертификат, "", "загрузка сертификатов JSON")
Rel(Очередь, ГоловнаяБаза_Реализация, "", "загрузка текущих реализаций сертификатов JSON")
Rel(Очередь, ГоловнаяБаза_Списание, "", "загрузка текущих списаний сертификатов JSON")

@enduml
